# Generated by Django 2.2.7 on 2019-12-14 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='webapp.Photo', verbose_name='Понравившаяся фотография'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_added', to=settings.AUTH_USER_MODEL, verbose_name='Автор лайка'),
        ),
    ]
