# Generated by Django 2.2.7 on 2019-12-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191214_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
